execute @e[type=item,name="warped wart block",r=6] ~ ~ ~ detect ~ ~ ~1 warped_wart_block 0 fill ~ ~ ~1 ~ ~ ~1 air 0 destroy
execute @e[type=item,name="warped wart block",r=6] ~ ~ ~ detect ~1 ~ ~1 warped_wart_block 0 fill ~1 ~ ~1 ~1 ~ ~1 air 0 destroy
execute @e[type=item,name="warped wart block",r=6] ~ ~ ~ detect ~-1 ~ ~1 warped_wart_block 0 fill ~-1 ~ ~1 ~-1 ~ ~1 air 0 destroy
execute @e[type=item,name="warped wart block",r=6] ~ ~ ~ detect ~1 ~ ~-1 warped_wart_block 0 fill ~1 ~ ~-1 ~1 ~ ~-1 air 0 destroy
execute @e[type=item,name="warped wart block",r=6] ~ ~ ~ detect ~-1 ~ ~-1 warped_wart_block 0 fill ~-1 ~ ~-1 ~-1 ~ ~-1 air 0 destroy
execute @e[type=item,name="warped wart block",r=6] ~ ~ ~ detect ~1 ~ ~ warped_wart_block 0 fill ~1 ~ ~ ~1 ~ ~ air 0 destroy
execute @e[type=item,name="warped wart block",r=6] ~ ~ ~ detect ~-1 ~ ~ warped_wart_block 0 fill ~-1 ~ ~ ~-1 ~ ~ air 0 destroy
execute @e[type=item,name="warped wart block",r=6] ~ ~ ~ detect ~ ~ ~-1 warped_wart_block 0 fill ~ ~ ~-1 ~ ~ ~-1 air 0 destroy
execute @e[type=item,name="warped wart block",r=6] ~ ~ ~ detect ~ ~-1 ~ warped_wart_block 0 fill ~ ~-1 ~ ~ ~-1 ~ air 0 destroy
execute @e[type=item,name="warped wart block",r=6] ~ ~ ~ detect ~ ~1 ~ warped_wart_block 0 fill ~ ~1 ~ ~ ~1 ~ air 0 destroy
execute @e[type=item,name="warped wart block",r=6] ~ ~ ~ detect ~ ~ ~1 warped_wart_block 0 fill ~ ~ ~2 ~ ~ ~2 air 0 destroy
execute @e[type=item,name="warped wart block",r=6] ~ ~ ~ detect ~1 ~ ~1 warped_wart_block 0 fill ~2 ~ ~2 ~2 ~ ~2 air 0 destroy
execute @e[type=item,name="warped wart block",r=6] ~ ~ ~ detect ~-1 ~ ~1 warped_wart_block 0 fill ~-2 ~ ~2 ~-2 ~ ~2 air 0 destroy
execute @e[type=item,name="warped wart block",r=6] ~ ~ ~ detect ~1 ~ ~-1 warped_wart_block 0 fill ~2 ~ ~-2 ~2 ~ ~-2 air 0 destroy
execute @e[type=item,name="warped wart block",r=6] ~ ~ ~ detect ~-1 ~ ~-1 warped_wart_block 0 fill ~-2 ~ ~-2 ~-2 ~ ~-2 air 0 destroy
execute @e[type=item,name="warped wart block",r=6] ~ ~ ~ detect ~1 ~ ~ warped_wart_block 0 fill ~2 ~ ~ ~2 ~ ~ air 0 destroy
execute @e[type=item,name="warped wart block",r=6] ~ ~ ~ detect ~-1 ~ ~ warped_wart_block 0 fill ~-2 ~ ~ ~-2 ~ ~ air 0 destroy
execute @e[type=item,name="warped wart block",r=6] ~ ~ ~ detect ~ ~ ~-1 warped_wart_block 0 fill ~ ~ ~-2 ~ ~ ~-2 air 0 destroy
execute @e[type=item,name="warped wart block",r=6] ~ ~ ~ detect ~ ~-1 ~ warped_wart_block 0 fill ~ ~-2 ~ ~ ~-2 ~ air 0 destroy
execute @e[type=item,name="warped wart block",r=6] ~ ~ ~ detect ~ ~1 ~ warped_wart_block 0 fill ~ ~2 ~ ~ ~2 ~ air 0 destroy