execute @e[type=item,r=5] ~ ~ ~ detect ~ ~ ~1 warped_stem -1 fill ~ ~ ~1 ~ ~ ~1 air 0 destroy
execute @e[type=item,r=5] ~ ~ ~ detect ~1 ~ ~1 warped_stem -1 fill ~1 ~ ~1 ~1 ~ ~1 air 0 destroy
execute @e[type=item,r=5] ~ ~ ~ detect ~-1 ~ ~1 warped_stem -1 fill ~-1 ~ ~1 ~-1 ~ ~1 air 0 destroy
execute @e[type=item,r=5] ~ ~ ~ detect ~1 ~ ~-1 warped_stem -1 fill ~1 ~ ~-1 ~1 ~ ~-1 air 0 destroy
execute @e[type=item,r=5] ~ ~ ~ detect ~-1 ~ ~-1 warped_stem -1 fill ~-1 ~ ~-1 ~-1 ~ ~-1 air 0 destroy
execute @e[type=item,r=5] ~ ~ ~ detect ~1 ~ ~ warped_stem -1 fill ~1 ~ ~ ~1 ~ ~ air 0 destroy
execute @e[type=item,r=5] ~ ~ ~ detect ~-1 ~ ~ warped_stem -1 fill ~-1 ~ ~ ~-1 ~ ~ air 0 destroy
execute @e[type=item,r=5] ~ ~ ~ detect ~ ~ ~-1 warped_stem -1 fill ~ ~ ~-1 ~ ~ ~-1 air 0 destroy
execute @e[type=item,r=5] ~ ~ ~ detect ~ ~-1 ~ warped_stem -1 fill ~ ~-1 ~ ~ ~-1 ~ air 0 destroy
execute @e[type=item,r=5] ~ ~ ~ detect ~ ~1 ~ warped_stem -1 fill ~ ~2 ~ ~ ~1 ~ air 0 destroy