execute @e[type=item,r=6] ~ ~ ~ detect ~ ~ ~1 log -1 fill ~ ~ ~1 ~ ~ ~1 air 0 destroy
execute @e[type=item,r=6] ~ ~ ~ detect ~1 ~ ~1 log -1 fill ~1 ~ ~1 ~1 ~ ~1 air 0 destroy
execute @e[type=item,r=6] ~ ~ ~ detect ~-1 ~ ~1 log -1 fill ~-1 ~ ~1 ~-1 ~ ~1 air 0 destroy
execute @e[type=item,r=6] ~ ~ ~ detect ~1 ~ ~-1 log -1 fill ~1 ~ ~-1 ~1 ~ ~-1 air 0 destroy
execute @e[type=item,r=6] ~ ~ ~ detect ~-1 ~ ~-1 log -1 fill ~-1 ~ ~-1 ~-1 ~ ~-1 air 0 destroy
execute @e[type=item,r=6] ~ ~ ~ detect ~1 ~ ~ log -1 fill ~1 ~ ~ ~1 ~ ~ air 0 destroy
execute @e[type=item,r=6] ~ ~ ~ detect ~-1 ~ ~ log -1 fill ~-1 ~ ~ ~-1 ~ ~ air 0 destroy
execute @e[type=item,r=6] ~ ~ ~ detect ~ ~ ~-1 log -1 fill ~ ~ ~-1 ~ ~ ~-1 air 0 destroy
execute @e[type=item,r=6] ~ ~ ~ detect ~ ~-1 ~ log -1 fill ~ ~-1 ~ ~ ~-1 ~ air 0 destroy
execute @e[type=item,r=6] ~ ~ ~ detect ~ ~1 ~ log -1 fill ~ ~2 ~ ~ ~1 ~ air 0 destroy
execute @e[type=item,r=6] ~ ~ ~ detect ~ ~ ~1 log2 -1 fill ~ ~ ~1 ~ ~ ~1 air 0 destroy
execute @e[type=item,r=6] ~ ~ ~ detect ~1 ~ ~1 log2 -1 fill ~1 ~ ~1 ~1 ~ ~1 air 0 destroy
execute @e[type=item,r=6] ~ ~ ~ detect ~-1 ~ ~1 log2 -1 fill ~-1 ~ ~1 ~-1 ~ ~1 air 0 destroy
execute @e[type=item,r=6] ~ ~ ~ detect ~1 ~ ~-1 log2 -1 fill ~1 ~ ~-1 ~1 ~ ~-1 air 0 destroy
execute @e[type=item,r=6] ~ ~ ~ detect ~-1 ~ ~-1 log2 -1 fill ~-1 ~ ~-1 ~-1 ~ ~-1 air 0 destroy
execute @e[type=item,r=6] ~ ~ ~ detect ~1 ~ ~ log2 -1 fill ~1 ~ ~ ~1 ~ ~ air 0 destroy
execute @e[type=item,r=6] ~ ~ ~ detect ~-1 ~ ~ log2 -1 fill ~-1 ~ ~ ~-1 ~ ~ air 0 destroy
execute @e[type=item,r=6] ~ ~ ~ detect ~ ~ ~-1 log2 -1 fill ~ ~ ~-1 ~ ~ ~-1 air 0 destroy
execute @e[type=item,r=6] ~ ~ ~ detect ~ ~-1 ~ log2 -1 fill ~ ~-1 ~ ~ ~-1 ~ air 0 destroy
execute @e[type=item,r=6] ~ ~ ~ detect ~ ~1 ~ log2 -1 fill ~ ~2 ~ ~ ~1 ~ air 0 destroy